name: Build pip Package
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build pip Package
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build pip Package
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: Upload pip Package to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pip-package
          path: dist/
      - name: Create a release and upload pip package
        if: github.event.pull_request.merged == true
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          token: ${{ secrets.TOKEN }}