name: Python Package using Conda

on:
    push:
      branches:
      - main
      - release/*
    pull_request:
        branches:
        - main
        - release/*
jobs:
    test:
        name: deploy to staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'
            - name: Add conda to system path
              run: |
                yum install gtk3
                wget http://releases.mozilla.org/pub/firefox/releases/116.0.3/linux-x86_64/zh-CN/firefox-116.0.3.tar.bz2
                tar jxpvf firefox-116.0.3.tar.bz2
                sudo ln -s /root/firefox/firefox /usr/bin/firefox
                apt-get install Xvfb
            - name: Install dependencies
              run: |
                pip install selenium
                pip install EasyProcess
                pip install xvfbwrapper
                pip install pyvirtualdisplay