name: Python Package using Conda

on:
    push:
      branches:
      - main
      - release/*
    pull_request:
        branches:
        - main
        - release/*
jobs:
    test:
        name: deploy to staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'
            - name: Install dependencies
              run: |
                pip install selenium
                pip install EasyProcess
                pip install xvfbwrapper
                pip install pyvirtualdisplay
            - name: run
              run: |
                cd src/
                chmod 755 ./release.py
                ./release.py ${{secrets.TESTURL}} ${{secrets.TESTUSERNAME}} ${{secrets.TESTPASSWORD}}
